services:
  courseservice:
    image: shbhmm/courserepo:v1
    build: ./src/CourseService
    container_name: courseservice
    ports:
      - "5001:8080"
    networks:
      - learning

  studentservice:
    image: shbhmm/studentrepo:v1
    build: ./src/StudentService
    container_name: studentservice
    ports:
      - "5002:8080"
    networks:
      - learning

  enrollmentservice:
    image: shbhmm/enrollmentrepo:v1
    build: ./src/EnrollmentService
    container_name: enrollmentservice
    ports:
      - "5003:8080"
    depends_on:
      - courseservice
      - studentservice
    networks:
      - learning

networks:
  learning:
    driver: bridge